name:                cube-mean-distance
version:             0.1.0.0
github:              "xayon40-12/cube-mean-distance"
license:             BSD3
author:              "Nathan Touroux"
maintainer:          "nathan.touroux@subatech.in2p3.fr"
copyright:           "Nathan Touroux (C) 2021"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/xayon40-12/cube-mean-distance#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- sort

library:
  source-dirs: src

executables:
  cube-mean-distance-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -O2
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cube-mean-distance

tests:
  cube-mean-distance-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cube-mean-distance
